### ISSUE TITLE
图像过大，显示不全

### ISSUE THREAD

**Issue by yxandam** [hzylmf/od-annotation#1]
您好，非常感谢您能贡献自己的工具。
我再使用的过程中遇到了一个问题。
如果我的图像是 2000*1000 的 那么在网页中会显示不全？
请问您有什么好的方法吗？

**Comment by hzylmf** [comment]
很高兴这个工具能对你有所帮助。这个问题有考虑到，应该做图片显示窗口的自适应，当时自己需要处理的样本没那么大，就没处理，后续会补充这个功能。
其实这种问题，建议还是等比例缩减一下图片尺寸，基于小尺寸的样本训练模型。识别时根据结果再根据当初的缩减比例还原真实目标尺寸。毕竟图片太大的话，目标检测时也会慢很多。

**Comment by yxandam** [comment]
非常感谢您的建议和意见，我考虑一下
